### ISSUE TITLE
Pin assignment to use ebyte sx1262 22 dbm module with ESP32

### ISSUE THREAD

**Issue by happytm** [beegee-tokyo/SX126x-Arduino#27]
Thank you for great library for SX126X chips. I am trying to build a PCB using above hardware. I need to have ST7789 TFT display, a MicroSD card socket and SX1262 Ebyte module in my project. I also need to use I2C for BME280 sensor & I2S bus for microphone and speaker. This is for home automation project but there is no need for Lorawan.

Do you think ESP32 can handle all these hardware devices?  If So what you suggest should be the optimum pin out ?

Thanks.

**Comment by beegee-tokyo** [comment]
If you have access to all GPIO's of the ESP32 (I guess so, because you say custom PCB) I would setup 2 SPI bus, one for the SX1262 and the other one for the display and the SD card.
The I2C should be no problem, but for I2S I have zero experience.
For the pin out, just make sure to keep GPIO's with boot functions ([List of reserved GPIO's](https://desire.giesecke.tk/index.php/2018/07/06/reserved-gpios/)) on the right level during booting.
