### ISSUE TITLE
Library dependencies

### ISSUE THREAD

**Issue by robsonos** [beegee-tokyo/SX126x-Arduino#56]
Hi Bernd,

If I add `SX126x-Arduino` to  the `lib_deps` in `platformio.ini`,  without including `<SX126x-Arduino.h>` to `main.cpp,` the compiler complains about missing the `SPI.h` and  the `Adafruit_TinyUSB.h` dependencies:

![image](https://user-images.githubusercontent.com/12877584/145702399-2a89e4a8-62f3-4975-ba34-3f107d417a4e.png)
![image](https://user-images.githubusercontent.com/12877584/145702383-9728c790-0e09-4e5d-9352-3e2c36a79898.png)

This can be easily fixed by adding those dependencies to `library.json`:

```
"dependencies": [
    {
      "name": "SPI",
      "frameworks": "arduino"
    },
    {
      "name": "Adafruit TinyUSB Library",
      "frameworks": "arduino"
    }
  ]
```

The motivation for this change is that we may have an `#ifdef` wrapping `#include <SX126x-Arduino.h>`, but we may still wan to keep `SX126x-Arduino` in `lib_deps`.
I am happy to create a PR if you agree with those changes.

Cheers,
Robson.

**Comment by beegee-tokyo** [comment]
Keep in mind that this library is not only for nRF52 MCU but as well supports ESP32, ESP8266 and RP2040.

Missing `Adafruit_TinyUSB.h` has to do with the Adafruit nRF52 BSP, out of some reason I do not get, they took `Serial` class out of the BSP. I do not want to add it as dependency, because it is only for nRF52 and will cause problems with other MCU platforms the library is supporting (currently ESP32 and RP2040)

Missing `SPI.h` is intentional to keep the library compatible with future Arduino architectures. E.g. in RP2040 BSP SPI class is named different (MbedSPI).

I am not sure why you would have the library in `lib_deps` if you do not use it. But I cannot implement your proposal without breaking other platforms.
