### ISSUE TITLE
A way to check if we are still in range of any LoraWAN base station?

### ISSUE THREAD

**Issue by NCPlyn** [beegee-tokyo/SX126x-Arduino#77]
Hi, is there a function or a way to check if we are still in range of any base station?
If no, I guess my option would be to do so the TTN sends something like a ACK packet or....

Disconnect/deinit the lora module and try to connect again once in while?
If so, is there a way/function to reset/rejoin the LoRaWAN network?

Thanks in advace.

**Comment by beegee-tokyo** [comment]
Hi @NCPlyn 

The only way I know is to use confirmed uplinks from the node to the TTN server. 
If you do not get the ACK from the server you are out of the coverage of gateways.

It is not a 100% sure method, because the uplink or the ACK transmission could fail because of other reasons.

You do not need to re-join to the server, just continue to send packets once you are in range of a gateway again.
